on:
    push:
        branches:
            - main



jobs:
    build_image:
        runs-on: ubuntu-latest
        steps:
            -
                # checkout repository
                name: Checkout
                uses: actions/checkout@v4
            -
                # login step
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{secrets.DOCKER_USERNAME}}
                    password: ${{secrets.DOCKER_PASSWORD}}
            -
                name: Setup Docker buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Build and push to docker hub
                uses: docker/build-push-action@v5
                with:
                    context: .
                    file: ./Dockerfile
                    push: true
                    tags: ${{secrets.DOCKER_USERNAME}}/scelloo_assessment:staging